import { color } from './components/styles/colors';
import {
  ChallengeType,
  ExecutionType,
  MypageHistoryType,
  NftType,
} from './types';

export const account = '0xfs312a2f3E829C0b614566B3E152e417d14q6EP3';

export const challengeList: Array<ChallengeType> = [
  {
    // id: '26',
    deposit: 3334,
    title: 'Participating in \nETH SEOUL',
    image: '/images/dummy/challenges/challenge_ethseoul.png',
    startDate: new Date('2023-06-04'),
    endDate: new Date('2023-06-04'),
    participants: 816,
    limit: 1000,
    hashtags: ['For now'],
    timeLeft: 1000000000,
    organizer: {
      name: 'ETH-SEOUL',
      image: '/images/dummy/organizer.png',
    },
    description:
      'Hello! 👋 We are ETH-SEOUL Hackathon Team "0xwanders"!  We\'ve prepared nfts for everyone to celebrate ETH-SEOUL Hackathon 🎉 Please upload a photo related to the ETH-SEOUL Hackathon, and you will be rewarded with an NFT!',
    nfts: [
      {
        title: 'eth-seoul',
        image: '/images/dummy/nfts/nft_1.GIF',
        description:
          "We'll pick 500 people\nwho succeed in this challenge\nand give them rtfkt nft",
      },
    ],
    minDeposits: 10,
    maxDeposits: 100,
    average: 70,
    background: '#32371F',
    fontColor: '#FFFFFF',
  },
  {
    // id: '0x6gr239290302e3',
    deposit: 3124,
    title: 'Jogging every \nmorning',
    image: '/images/dummy/challenges/challenge_6.png',
    startDate: new Date('2023-03-10'),
    endDate: new Date('2023-03-15'),
    participants: 816,
    limit: 1000,
    hashtags: ['For 2 weeks', 'weekdays'],
    timeLeft: 1000000000,
    organizer: {
      name: 'NIKE',
      image: '/images/dummy/organizer.png',
    },
    description:
      'Hello, we are Nike! Are you ready to work out passionately with Nike for two weeks? Confirm your daily exercise and receive a prize and an RTKFT NFT in two weeks! This is the perfect opportunity to develop a healthy exercise habit with Nike!',
    nfts: [
      {
        title: 'eth-seoul',
        image: '/images/dummy/nfts/nft_1.GIF',
        description:
          "We'll pick 500 people\nwho succeed in this challenge\nand give them rtfkt nft",
      },
    ],
    minDeposits: 0.04,
    maxDeposits: 1000,
    average: 23,
    background: '#32371F',
    fontColor: '#FFFFFF',
  },
  {
    // id: '0x6gr9209sdvsdv',
    deposit: 1093,
    title: 'Read 10 pages \nevery day',
    image: '/images/dummy/challenges/challenge_5.png',
    startDate: new Date('2023-03-08'),
    endDate: new Date('2023-03-09'),
    participants: 816,
    limit: 1000,
    hashtags: ['For 2 weeks', 'weekdays'],
    timeLeft: 1000000000,
    organizer: {
      name: 'NIKE',
      image: '/images/dummy/organizer.png',
    },
    description:
      'Hello, we are Nike! Are you ready to work out passionately with Nike for two weeks? Confirm your daily exercise and receive a prize and an RTKFT NFT in two weeks! This is the perfect opportunity to develop a healthy exercise habit with Nike!',
    nfts: [
      {
        title: 'eth-seoul',
        image: '/images/dummy/nfts/nft_1.GIF',
        description: 'Achieved 5 times of\nexercise challenge',
      },
    ],
    minDeposits: 0.04,
    maxDeposits: 1000,
    average: 23,
    background: '#E8DDD5',
    fontColor: color.primary,
  },
  {
    // id: '0x6grsdf9023ier23',
    deposit: 6319.09,
    title: 'Working out \nevery day',
    image: '/images/dummy/challenges/challenge_1.png',
    startDate: new Date('2023-01-10'),
    endDate: new Date('2023-02-15'),
    participants: 816,
    limit: 1000,
    hashtags: ['For 2 weeks', 'weekdays'],
    timeLeft: 1000000000,
    organizer: {
      name: 'NIKE',
      image: '/images/dummy/organizer.png',
    },
    description:
      'Hello, we are Nike! Are you ready to work out passionately with Nike for two weeks? Confirm your daily exercise and receive a prize and an RTKFT NFT in two weeks! This is the perfect opportunity to develop a healthy exercise habit with Nike!',
    nfts: [
      {
        title: 'ethseoul',
        image: '/images/dummy/nfts/nft_1.GIF',
        description: 'Achieved 5 times of\nexercise challenge',
      },
    ],
    minDeposits: 0.04,
    maxDeposits: 1000,
    average: 23,
    background: '#1D1D1D',
    fontColor: '#FFFFFF',
  },
  {
    // id: '0x6gr434902rj23i',
    deposit: 320.32,
    title: 'Waking up early in \nthe morning',
    image: '/images/dummy/challenges/challenge_4.png',
    startDate: new Date('2023-05-10'),
    endDate: new Date('2023-05-15'),
    participants: 816,
    limit: 1000,
    hashtags: ['For 2 weeks', 'weekdays'],
    timeLeft: 1000000000,
    organizer: {
      name: 'NIKE',
      image: '/images/dummy/organizer.png',
    },
    description:
      'Hello, we are Nike! Are you ready to work out passionately with Nike for two weeks? Confirm your daily exercise and receive a prize and an RTKFT NFT in two weeks! This is the perfect opportunity to develop a healthy exercise habit with Nike!',
    nfts: [
      {
        title: 'ethseoul',
        image: '/images/dummy/nfts/nft_1.GIF',
        description: 'Achieved 5 times of\nexercise challenge',
      },
    ],
    minDeposits: 0.04,
    maxDeposits: 1000,
    average: 23,
    background: '#1D1D1D',
    fontColor: color.white,
  },
  {
    // id: '0x6gr3290392rwf',
    deposit: 7439.4,
    title: 'Using stairs instead \nof elevators',
    image: '/images/dummy/challenges/challenge_3.png',
    startDate: new Date('2023-01-13'),
    endDate: new Date('2023-01-14'),
    participants: 816,
    limit: 1000,
    hashtags: ['For 2 weeks', 'weekdays'],
    timeLeft: 1000000000,
    organizer: {
      name: 'NIKE',
      image: '/images/dummy/organizer.png',
    },
    description:
      'Hello, we are Nike! Are you ready to work out passionately with Nike for two weeks? Confirm your daily exercise and receive a prize and an RTKFT NFT in two weeks! This is the perfect opportunity to develop a healthy exercise habit with Nike!',
    nfts: [
      {
        title: 'ethseoul',
        image: '/images/dummy/nfts/nft_1.GIF',
        description: 'Achieved 5 times of\nexercise challenge',
      },
    ],
    minDeposits: 0.04,
    maxDeposits: 1000,
    average: 23,
    background: '#5F5F5F',
    fontColor: '#FFFFFF',
  },
  {
    // id: '0x6gr23929v23riojfwe',
    deposit: 432.1,
    title: 'Read a magazine \nevery day',
    image: '/images/dummy/challenges/challenge_2.png',
    startDate: new Date('2023-05-02'),
    endDate: new Date('2023-05-15'),
    participants: 816,
    limit: 1000,
    hashtags: ['For 2 weeks', 'weekdays'],
    timeLeft: 1000000000,
    organizer: {
      name: 'NIKE',
      image: '/images/dummy/organizer.png',
    },
    description:
      'Hello, we are Nike! Are you ready to work out passionately with Nike for two weeks? Confirm your daily exercise and receive a prize and an RTKFT NFT in two weeks! This is the perfect opportunity to develop a healthy exercise habit with Nike!',
    nfts: [
      {
        title: 'ethseoul',
        image: '/images/dummy/nfts/nft_1.GIF',
        description: 'Achieved 5 times of\nexercise challenge',
      },
    ],
    minDeposits: 0.04,
    maxDeposits: 1000,
    average: 23,
    background: '#8A9298',
    fontColor: '#FFFFFF',
  },
];

export const executions: Array<ExecutionType> = [
  {
    id: 'ox3202efef34r21',
    account: '0xfs312a2f3E829C0b614566B3E152e417d14q6EP3',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_1.jpeg',
    imageName: 'execution_1.jpeg',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202efef34r21232323',
    account: '0xfs312a2f3E829C0b614566B3E152e417d14q6EP3',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_2.jpeg',
    imageName: 'execution_2.jpeg',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202efef34r3433',
    account: '0xfs312a2f3E829C0b614566B3E152e417d14q6EP3',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_3.jpeg',
    imageName: 'execution_3.jpeg',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202efef3434ffs1',
    account: '0xds542a2f3E829C0b614566B3E152e417d14q6EP3',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_4.jpeg',
    imageName: 'execution_4.jpeg',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202efef3vsvsdvs21',
    account: '0xa2472a2f3E829C0b614566B3E152e417d14q6ed3',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_5.jpeg',
    imageName: 'execution_5.jpeg',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202egeri3049gj',
    account: '0x93df32a2f3E829C0b614566B3E152e417d14q637d',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_6.jpeg',
    imageName: 'execution_6.jpeg',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202efe4kfge90jbdk',
    account: '0xfs312a2f3E829C0b614566B3E152e417d14q6de23',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_7.jpeg',
    imageName: 'execution_7.jpeg',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202efef3rf98vdn',
    account: '0xfs312a2f3E829C0b614566B3E152e417d1432ab29',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_8.jpeg',
    imageName: 'execution_8.jpeg',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202einrrerferf8vdn',
    account: '0xfs219a2f3E829C0b614566B3E152e417d66B3E112',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_9.jpeg',
    imageName: 'execution_9.png',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202egeri3049gj',
    account: '0x23fd2a2f3E829C0b614566B3E152e417d14q6EP3',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_10.jpeg',
    imageName: 'execution_10.jpeg',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202efe4kfge90jbdk',
    account: '0xfs312a2f3E829C0b614566B3E152e417d14q6EP3',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_11.jpeg',
    imageName: 'execution_11.jpeg',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202efef3rf98vdn',
    account: '0xfs312a2f3E829C0b614566B3E152e417d14q6EP3',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_12.jpeg',
    imageName: 'execution_12.jpeg',
    status: 'success',
    date: new Date(),
  },
  {
    id: 'ox3202einrrerferf8vdn',
    account: '0xfs312a2f3E829C0b614566B3E152e417d14q6EP3',
    challengeId: '16',
    count: 10,
    imagePath: '/images/dummy/executions/execution_13.jpeg',
    imageName: 'execution_13.png',
    status: 'success',
    date: new Date(),
  },
];

export const myNfts: Array<NftType> = [
  {
    hash: '0xfhfwiljfo32ughwke09vdjnSJHFK4343jkfjw',
    image: '/images/dummy/my-nfts/my_nft_1.GIF',
  },
  {
    hash: '0xfhfwiljfo32uJIOERJOWI3443343jkfjw',
    image: '/images/dummy/my-nfts/my_nft_2.png',
  },
  {
    hash: '0xfhfwivdklf983894jheuvdjnSJHFK4343jkfjw',
    image: '/images/dummy/my-nfts/my_nft_3.png',
  },
  {
    hash: '0xffnji34NJKVEV4343MKLCE434343mkleejw',
    image: '/images/dummy/my-nfts/my_nft_4.png',
  },
  {
    hash: '0xdvdbgfbjiomNJFK3434545443jkfjw',
    image: '/images/dummy/my-nfts/my_nft_5.png',
  },
  {
    hash: '0xfhfwiljfo32ughwke09vdfevev4343jkfjw',
    image: '/images/dummy/my-nfts/my_nft_6.png',
  },
];

export const mypageHistories: Array<MypageHistoryType> = [
  {
    challengeId: '0x6grsdf9023ier23',
    balance: 26.7,
  },
  {
    challengeId: '0x6gr3290392rwf',
    balance: 73.23,
  },
  {
    challengeId: '0x6gr239290302e3',
    balance: 736.23,
  },
];
